### ISSUE TITLE
Agree on an ID scheme for new ontology

### ISSUE THREAD

**Issue by dosumis** [obophenotype/insect_neuroanatomy_ontology#3]
INO_ ?

URI scheme?

Redirects?

**Comment by cmungall** [comment]
OINC: Ontology of Insect Neuroanatomy and Cells

But INO is probably better. Email obo-discuss with request. PURLs and Redirects follow from there

Last chance to claim a broader taxon scope...

**Comment by cmungall** [comment]
I see someone has claimed NIN http://insectbraindb.org/neurons/index/species/?page=2, that would have been my next choice...

**Comment by dosumis** [comment]
We have decided to give these Uberon IDs as part of this project: https://github.com/obophenotype/insect-anatomy-ontology
